/**
 * autostart.ts — Register/unregister the daemon to start on user login.
 *
 * Windows:  creates a silent VBScript in the Startup folder
 * macOS:    creates a launchd agent plist (TODO)
 * Linux:    creates a systemd --user service (TODO)
 */

import { existsSync, writeFileSync, rmSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Windows Startup folder (%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup) */
function windowsStartupDir(): string {
  const appData = process.env.APPDATA || join(homedir(), 'AppData', 'Roaming');
  return join(appData, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup');
}

function vbsPath(): string {
  return join(windowsStartupDir(), 'saros-proxy-daemon.vbs');
}

/**
 * Resolve the saros-proxy command path.
 * On Windows with a global install this is typically %APPDATA%\npm\saros-proxy.cmd.
 * Falls back to the bare command name which works if the npm bin directory is on PATH.
 */
function resolveCommand(): string {
  // When running via `node dist/cli/autostart.js`, use the sibling dist/index.js
  // so we don't depend on PATH resolution.
  const viaDist = join(import.meta.dirname!, '..', '..', 'dist', 'index.js');
  if (existsSync(viaDist)) {
    return `"${process.execPath}" "${viaDist}"`;
  }
  // Fallback: assume `saros-proxy` is on PATH
  return 'saros-proxy';
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function autostartInstall(port?: number): void {
  const command = resolveCommand();
  const portArg = port ? ` --port ${port}` : '';
  // VBScript strings use " as delimiter; inline quotes must be doubled ("").
  const escapedCommand = command.replace(/"/g, '""');
  const vbs = [
    "' Saros proxy auto-start (generated by `saros-proxy autostart install`)",
    'Dim shell',
    'Set shell = CreateObject("WScript.Shell")',
    `shell.Run "${escapedCommand} start${portArg}", 0, False`,
    'Set shell = Nothing',
  ].join('\n');

  writeFileSync(vbsPath(), vbs, 'utf-8');
  console.log(`Auto-start installed: ${vbsPath()}`);
}

export function autostartUninstall(): void {
  const path = vbsPath();
  if (!existsSync(path)) {
    console.log('No auto-start entry found.');
    return;
  }
  rmSync(path);
  console.log(`Auto-start removed: ${path}`);
}

export function autostartStatus(): void {
  const path = vbsPath();
  if (existsSync(path)) {
    const content = readFileSync(path, 'utf-8').trim();
    const match = content.match(/start(--port (\d+))?/);
    const portInfo = match?.[2] ? ` on port ${match[2]}` : '';
    console.log(`Auto-start is enabled${portInfo}. File: ${path}`);
  } else {
    console.log('Auto-start is not installed.');
  }
}
